index_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - i_mcp_yaw
    - i_mcp_pitch
    - i_pip_pitch
    - i_dip_pitch
  gains:
    i_mcp_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i_mcp_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i_pip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    i_dip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
middle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - m_mcp_yaw
    - m_mcp_pitch
    - m_pip_pitch
    - m_dip_pitch
  gains:
    m_mcp_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_mcp_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_pip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_dip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ring_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_mcp_yaw
    - r_mcp_pitch
    - r_pip_pitch
    - r_dip_pitch
  gains:
    r_mcp_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_mcp_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_pip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_dip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
pinky_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - s_mcp_yaw
    - s_mcp_pitch
    - s_pip_pitch
    - s_dip_pitch
  gains:
    s_mcp_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    s_mcp_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    s_pip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    s_dip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
thumb_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - t_mcp_pitch
    - t_mcp_yaw
    - t_pip_pitch
  gains:
    t_mcp_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    t_mcp_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    t_pip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1