simple_robot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  left_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_drive
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_drive
    pid: {p: 100.0, i: 0.01, d: 10.0}
